### ISSUE TITLE
0.7 

### ISSUE THREAD

**Issue by hustf** [Ismael-VC/InfixFunctions.jl#1]
On Julia v"0.7.0-DEV.2058":

```
Pkg.clone("https://github.com/Ismael-VC/InfixFunctions.jl")
using InfixFunctions
@infix fo(x,y)= x+y
WARNING: `isdefined(:symbol)` is deprecated, use `@isdefined symbol` instead
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:68
 [2] eval(::Module, ::Expr) at .\repl\REPL.jl:3
 [3] eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\repl\REPL.jl:69
 [4] macro expansion at .\repl\REPL.jl:100 [inlined]
 [5] (::getfield(Base.REPL, Symbol("##1#2")){Base.REPL.REPLBackend})() at .\event.jl:96
in expression starting at no file:82
ERROR: type #fo has no field operator
```

**Comment by Ismael-VC** [comment]
@hustf could you please try again?, I have fixed the operator field error.

The deprecation warnings are anoter issue, Compat.jl doesn't have yet a way to make this cross version like: `@compat @isdefined foo` for 0.6 yet AFAICT.

But that is expected from the development branch. If you find those annoying you could try another of my packages Suppressor.jl (that one is registered!)

So you could try: `@suppress_err @infix foo(x,y) = x+y`

* https://github.com/Ismael-VC/Suppressor.jl

I'll enable CI tomorrow for automated testing on all supported platforms and current versions.

**Comment by hustf** [comment]
It's fixed now. Depwarns remain, of course. I use Windows, in case you are thinking about testing on appveyor too.
Thanks for the depwarn tip!
